### ISSUE TITLE
utils module missing after install + run in terminal

### ISSUE THREAD

**Issue by ezmegy** [chamkank/hone#2]
Hi,

I've just followed the install steps and can't seem to get past some missing stuff.
This is the message I get (on Mac, High Sierra 10.13.3):

`  File "/usr/local/bin/hone", line 7, in <module>
    from hone.__main__ import main
  File "/Library/Python/2.7/site-packages/hone/__init__.py", line 1, in <module>
    from hone.hone import Hone
  File "/Library/Python/2.7/site-packages/hone/hone.py", line 1, in <module>
    from hone.utils import csv_utils
ImportError: No module named utils`

Any ideas what I should do (differently)?

**Comment by chamkank** [comment]
Sorry for the delayed response! It looks like you're using Python `2.7`, this module requires Python `3+`.
